### ISSUE TITLE
Change chrony configuration to avoid NTP access worldwide

### ISSUE THREAD

**Issue by AlexandreJean** [Azure/cyclecloud-marketplace-image#1]
Hi CycleCloud team, 
I will suggest to update the /etc/chrony.conf as follow [here](https://github.com/Azure/az-hop/blob/c7663b68c44d519ae57d3ced4df4c92471a82864/playbooks/chrony.yml) into the marketplace image.
Indeed I am working with a customer to avoid any external access, and Microsoft is providing guidance to rely on the VM host to sync the date and time. I think it is a perfect solution to avoid external access.

**Comment by atomic-penguin** [comment]
I can't recall if you, and I, discussed this. I think this is probably out of scope for the CycleCloud team. But it may be worth getting onto the backlog for other Azure HPC VM images on which CycleCloud's marketplace image is based. Feel free to ping me on Teams and I'll put you in touch with an Azure HPC PM to coordinate.
